[mypy]
python_version = 3.12
ignore_missing_imports = True
show_error_codes = True
warn_unused_ignores = False
warn_redundant_casts = True
warn_unreachable = True
no_implicit_optional = True
check_untyped_defs = True
files = accounts, activity, assignments, config, courses, discussions, materials, messaging, api, ui
exclude = (?x)
  (^|.*/|.*\\)tests(/|\\)  # any tests dir
  | ^conftest\.py$
plugins = mypy_django_plugin.main

[mypy-django.*]
ignore_missing_imports = True

[mypy-rest_framework.*]
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings.dev

[mypy-tests.*]
ignore_errors = True

[mypy-*.tests.*]
ignore_errors = True

[mypy-accounts.utils]
disallow_untyped_defs = True

[mypy-assignments.services]
disallow_untyped_defs = True
