# Generated by Django 5.1.15 on 2026-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_merge_0002_course_syllabus_outcomes_0002_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
