# Generated by hand to add indexes on Course and Feedback
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_language_course_level_course_subject_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["subject", "level", "language"], name="course_subj_lvl_lang_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["course", "student"], name="feedback_course_student_idx"),
        ),
    ]
