# Generated by Django 5.1.15 on 2026-03-05 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_indexes_course_and_feedback"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_cou_subject_47c6e5_idx",
            old_name="course_subj_lvl_lang_idx",
        ),
        migrations.RenameIndex(
            model_name="feedback",
            new_name="courses_fee_course__46af5b_idx",
            old_name="feedback_course_student_idx",
        ),
    ]
