# Generated by Django 5.1.15 on 2026-03-05 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_feedback_constraints_and_created_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedback",
            name="courses_fee_created_idx",
        ),
    ]
