# Generated by Django 5.1.15 on 2026-02-28 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_assignment_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
