# Generated by hand to add useful DB indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0009_attempts_policy_and_explanation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "is_published", "deadline"], name="asmt_course_pub_deadline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["assignment", "student"], name="attempt_asg_stu_idx"),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["released", "assignment"], name="attempt_rel_asg_idx"),
        ),
    ]
