# Generated by Django 5.1.15 on 2026-03-05 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0010_assignment_attempt_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assignment",
            new_name="assignments_course__333906_idx",
            old_name="asmt_course_pub_deadline_idx",
        ),
        migrations.RenameIndex(
            model_name="attempt",
            new_name="assignments_assignm_97c40f_idx",
            old_name="attempt_asg_stu_idx",
        ),
        migrations.RenameIndex(
            model_name="attempt",
            new_name="assignments_release_d8b165_idx",
            old_name="attempt_rel_asg_idx",
        ),
    ]
