# Generated by Django 5.1.15 on 2026-02-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("enrolment", "Enrolment"), ("material", "Material"), ("grade", "Grade")],
                max_length=20,
            ),
        ),
    ]
